WIP: chore(flags): add new function to split the message flags to an array
Sonia-corporation/il-est-midi-discord pull request #906
Opened 2020-09-05 21:47 UTC by C0ZEN

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [guidelines](https://github.com/Sonia-corporation/il-est-midi-discord/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added/updated (for bugfix/feature)
- [ ] Docs have been added/updated (for bugfix/feature)

## PR Type
What kind of change does this PR introduce?

- [ ] Feature (a new feature)
- [ ] Bugfix (a bug fix)
- [ ] Style (changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc))
- [ ] Refactor (a code change that neither fixes a bug nor adds a feature)
- [ ] Perf (a code change that improves performance)
- [ ] Test (adding missing tests or correcting existing tests)
- [ ] Build (changes that affect the build system, CI configuration or external dependencies)
- [ ] Docs (changes that affect the documentation)
- [ ] Chore (anything else), please describe:

## What is the current behavior?

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2020-09-09 08:54 UTC, C0ZEN commented on src/features/discord/messages/functions/commands/flags/discord-command-get-flag-value.ts
> +  if (isFlag(messageFlag)) {
Refactor to add more clean-code for the whole function.

2020-09-09 08:56 UTC, C0ZEN commented on src/features/discord/messages/services/command/feature/features/noon/classes/discord-message-command-feature-noon-enabled.ts
> +    value: Readonly<string | null | undefined> = undefined
Make it optional instead of assigning undefined

2020-09-09 08:56 UTC, C0ZEN commented on src/features/discord/messages/services/command/feature/features/noon/classes/discord-message-command-feature-noon-enabled.ts
> +    LoggerService.getInstance().debug({
More clean code

2020-09-09 18:22 UTC, asmodee-bellanie requested changes
First review from Hell!

2020-09-09 18:22 UTC, asmodee-bellanie commented on CONTRIBUTING.md
> +I think that a workaround with types can be made but all I was not able to do it without losing the links between models and data.
Yo WTF? What was the initial sentence here? 🤔

2020-09-09 18:22 UTC, asmodee-bellanie commented on package.json
> +    "madge:image": "madge ./src/ --extensions ts,js --image ./dist/dependencies-graph.svg --warning"
Could I have a private lesson of what you added here, please? :3

2020-09-10 18:09 UTC, vvalembois approved these changes

2020-09-10 20:01 UTC, merged